### PR TITLE
Elaborated Keycloak auth restrictions by user group in the documentation.

### PR DESCRIPTION
**Pull request by axl8713**
## Description

Elaborated the documentation for the Keycloak endpoint about authorization restrictions by user group.

## Motivation and Context

The documentation of the user group access restrictions for the Keycloak endpoint was not as clear as the one for the other endpoints.

## How Has This Been Tested?

Checked the Markdown preview.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by NickMeves** [comment]
I'm gonna hold on reviewing this until this PR wraps up and merges: https://github.com/oauth2-proxy/oauth2-proxy/pull/861

It might change the underlying functionality so we'd need to adjust the documentation.

**Comment by NickMeves** [comment]
Do the updates I made to the docs related to this refactor cover your concerns? https://github.com/oauth2-proxy/oauth2-proxy/pull/953/files

**Comment by axl8713** [comment]
Yes. Nice work.

**Comment by NickMeves** [comment]
Closing in favor of other Keycloak PR that updated these docs.

**Pull request closed without merging**
