### PR TITLE
Changing user field type to text

### LINKED ISSUE #1336: Username field type is email when htpasswd is enabled
When the htpasswd file is provided, the username+password fields are shown but the username is checking for a an email.

## Expected Behavior

When the htpassword file is provided, I should be able to login with a account which doesn't contains an '@'

## Current Behavior

The GUI is complaining that username doesn't contain an '@' and doesn't let the user in

## Possible Solution

Remove type="email" in HTML

## Steps to Reproduce (for bugs)

- Version used: 7.1.3

### PR DESCRIPTION
**Pull request by pburgisser**
Fix #1336 

## Description

Change username field from email to text when htpasswd is enabled

## Motivation and Context

The username field is requesting an email as the username where a username may now contain an '@'

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Review by NickMeves — COMMENTED** [review]
How does this work without an email?

(Excuse my ignorance, I've never really used htpasswd functionality in practice).

I thought we required an email for login with our email domain validation unless you set a ton of flags to allowlist * and override with user/sub claims?

**Comment by pburgisser** [comment]
As the htpasswd is a static user:password file, provided by the admin of oauth, I don't see the need to validate any allowed domain.

Also, I've never seen email in a htpasswd file, but I might be wrong.

**Comment by NickMeves** [comment]
Ah, yup - just User: https://github.com/oauth2-proxy/oauth2-proxy/blob/5928fe5485ddec4a4e31dc25e3ce6e559a11776a/oauthproxy.go#L590

Did you want to add a changelog entry for attribution (not required)? Otherwise I'll merge.

**Comment by pburgisser** [comment]
@NickMeves I have updated the changelog accordingly. Cheers!

**Review by JoelSpeed — APPROVED** [review]
Thanks, let's merge this

**Pull request merged**
