### PR TITLE
Mention value seperation for plural environment variables

### PR DESCRIPTION
**Pull request by TuningYourCode**
## Description

Improve documentation to mention how values should be given in plural environment variables.

## Motivation and Context

We needed to set `OAUTH2_PROXY_SKIP_AUTH_ROUTES` but the documentation was not clear how to seperate the values.

## How Has This Been Tested?

Was tested in our docker setup.

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.
- [ ] I have written tests for my code changes.

### CODE REVIEW

**Comment by TuningYourCode** [comment]
This PR documents the "findings" in #2672

**Review by tuunit — CHANGES_REQUESTED** [review]
Please add the same change to the v7.6 docs.

**Comment by TuningYourCode** [comment]
What do you mean by adding it to the v7.6 docs is there another location i have to change?

**Comment by ianroberts** [comment]
You just need to make the same edits to the corresponding file under `docs/versioned_docs/version-7.6.x`.

**Comment by tuunit** [comment]
@TuningYourCode as @ianroberts mentioned you need to make the same changes in `docs/versioned_docs/version-7.6.x`.

The docs are versioned the latest doc for version `7.6.x` is stored in the directory above.
The file you changed is for upcoming major releases `8.x.x`

image

**Comment by TuningYourCode** [comment]
Thank you i just wasn't aware of `docs/versioned_docs/` but makes sense after all :)

**Review by tuunit — APPROVED** [review]

**Review by tuunit — APPROVED** [review]

**Pull request merged**
