### PR TITLE
Make sure JWT is never expired

### PR DESCRIPTION
**Pull request by stippi2**
## Description

This change makes sure session expiry takes precedence over periodic session refresh.

## Motivation and Context

The session expiry is initialized from the JWT expiry. However oauth2-proxy previously only refreshed sessions based on the configuration, and it's possible to disable the refresh completely. My intuitive understanding was that JWT expiry was then still taken into account, and that periodic refresh was something "on top" of automatic session refresh for expired JWTs. That was not the case.

Previously it was possible to completely disable refresh, or use an expired JWT for a period of time if JWT expiry happened to overlap with periodic refresh.

I would like to get feedback first. If this change makes sense, I will provide test coverage. Please wait with merging until there is test-coverage.

## How Has This Been Tested?

I've tested this with JWTs that have a very short expiry and stepping through the debugger and validating sessions are refreshed when necessary.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
With this change, this will prevent users from disabling the refresh right? I believe some users don't care about refreshing and therefore are quite happy to have expired tokens and just keep the cookie alive as long as they like, perhaps they only care about the name and don't need additional validation from the IDP that the user is still logged in.

What happens in this case when the JWT is expired and there is no refresh token?

**Comment by stippi2** [comment]
One good reason for making sure the JWT is never expired is that it may be forwarded to another system, e.g. for principle propagation. That is how we noticed a problem in the first place. The other system rejected the JWT because it was expired. If JWT expiry is a thing, why would OAuth2-Proxy ignore it by default and only use its own periodic session refresh that is most likely not aligned with the JWT expiry at all?

**Comment by stippi2** [comment]
I would love to get feedback on my argument above. I am open to implementing it in a different way that takes more needs into account.

**Comment by aschleck** [comment]
Not entirely sure if this is the same problem, but the current logic in oauth2-proxy was deeply surprising to me. I had a basic setup of oauth2-proxy passing credentials via header to Kubernetes Dashboard and was very confused when it showed me as unauthorized. I was even more confused when the Kubernetes apiserver logs showed me my token was expired. Eventually I found the --cookie-refresh flag but it was completely non-obvious.

**Comment by stippi2** [comment]
It sounds like exactly the same problem.

**Comment by stippi** [comment]
This issue is not stale. I would still like to receive feedback, see comments above.

**Comment by JoelSpeed** [comment]
Sorry, I've been very busy recently and not had time to contribute here, aiming to spend time next week on the project

**Comment by stippi** [comment]
No pressure! Am I just not a huge fan of the stale bot.

**Comment by JoelSpeed** [comment]
Looking at https://github.com/oauth2-proxy/oauth2-proxy/blob/c5a98c6d03781476021107772a150ba2acb39206/pkg/middleware/stored_session.go#L171-L173, I think this is probably an ok change. If we do attempt to refresh a session and the provider doesn't refresh it, we check that the session is still valid, if it's expired, we reject the session. So this shouldn't change the behaviour negatively I don't think.

Have you considered this part of the code https://github.com/oauth2-proxy/oauth2-proxy/blob/c5a98c6d03781476021107772a150ba2acb39206/pkg/middleware/stored_session.go#L114-L117

I think we probably want to change this so that we only skip attempting to refresh if refresh is explicitly disabled, and defer to the provider implementation to determine if the session is old enough to be refreshed, WDYT?

**Comment by stippi2** [comment]
> Looking at
> 
> https://github.com/oauth2-proxy/oauth2-proxy/blob/c5a98c6d03781476021107772a150ba2acb39206/pkg/middleware/stored_session.go#L171-L173
> 
> , I think this is probably an ok change. If we do attempt to refresh a session and the provider doesn't refresh it, we check that the session is still valid, if it's expired, we reject the session. So this shouldn't change the behaviour negatively I don't think.

Do you mean there is already an example in the code where the session was refreshed due to being invalid? So that makes you confident that's OK to introduce the change in this PR?

> https://github.com/oauth2-proxy/oauth2-proxy/blob/c5a98c6d03781476021107772a150ba2acb39206/pkg/middleware/stored_session.go#L114-L117
> 
> I think we probably want to change this so that we only skip attempting to refresh if refresh is explicitly disabled, and defer to the provider implementation to determine if the session is old enough to be refreshed, WDYT?

Sorry, I don't yet understand what you are proposing.

**Comment by JoelSpeed** [comment]
> Do you mean there is already an example in the code where the session was refreshed due to being invalid? So that makes you confident that's OK to introduce the change in this PR?

Currently, if we attempt to refresh a session, and the provider doesn't actually refresh it, we then check if the session is valid. If it has expired, we log the user out. With your change, rather than logging the user out, we at least attempt to refresh their session, so I think this is an improvement in the logic

> Sorry, I don't yet understand what you are proposing.

I'm basically thinking that in that linked code we need to remove the second clause. This code currently skips the code you modified if we think the session isn't old enough to be refreshed

**Comment by PSanetra** [comment]
@stippi2 Do you think the concern mentioned in this comment is valid? https://github.com/oauth2-proxy/oauth2-proxy/pull/1318#issuecomment-1040016499

**Comment by stippi2** [comment]
Still valid.

**Comment by stippi2** [comment]
Still relevant.

**Comment by JoelSpeed** [comment]
Coming back to this, what are we trying to do with the latest version of this PR? Can we get it fixed up against the latest master?

**Comment by stippi2** [comment]
> Coming back to this, what are we trying to do with the latest version of this PR? Can we get it fixed up against the latest master?

Sure, I've just merged with master. IMHO, in the isolated `needsRefresh()` method, it becomes even more obvious that the proposed fix is correct.

**Comment by JoelSpeed** [comment]
Please add a changelog entry and, if possible, update the tests to reflect the change so that we don't accidentally undo this change later, then I'll get this merged

**Pull request closed without merging**
