### PR TITLE
Use the httputil.NewSingleHostReverseProxy instead of yhat/wsutil for …

### LINKED ISSUE #1347: After forwarding a websocket request which fails, subsequent reuse of the connection does not get auth headers
I'm using oauth2-proxy as a gateway for Kubeapps. On some (but only some) releases, I would get redirected to the login page when trying to get the release status. I've tracked this down to three bugs in three projects, all of which collude to cause this particular problem. This issue is about the bug in oauth-proxy2.

## Expected Behavior

If oauth2-proxy gets a request to proxy a web socket and the upstream server returns a 4xx or 5xx status code then either the downstream connection should be closed or the state should be reset so that subsequent requests are translated.

## Current Behavior

It *seems* that as soon as oauth2-proxy sees the 'Connection: upgrade' and 'Upgrade: websocket' headers and is able to connect to the upstream server, it treats the stream as a tunnel. If the upstream server replies with a 404, for example, and the downstream client sends a second request on the connection, it will be echoed directly to the upstream server, without translation. Crucially, it will be missing the 'Authorization: Bearer ...' token, instead just forwarding on the cookie the downstream client included in the request.

## Possible Solution

I have no experience with Go, unfortunately. It looks like the code in pkg/upstream/http.go needs to confirm that the connection has succeeded. It's possible that this is actually a bug in the net/http/httputil package

## Steps to Reproduce (for bugs)

This is unfortunately quite hard to set up in a way that's observable. It took me a lot of fiddling around with tcpdump to get to the bottom of it. I'm hoping that the description above is enough to trigger a realisation in someone familiar with the code.

What I did to reproduce it was to get a shell in the pod running oauth2-proxy, set up tcpdump on the loopback interface, then telnet to localhost:3000 (which is the port oauth2-proxy is bound to) and then paste in this message:
```
GET /api/clusters/default/api/v1/namespaces/default/serviceaccounts?watch=true&fieldSelector=metadata.name%3Dr2-promtail HTTP/1.1
Host: kubeapps.example.com
Upgrade: websocket
Connection: upgrade
X-Request-ID: b00b559b26c3e599e9541b16c55b7518
X-Real-IP: 10.244.0.0
X-Forwarded-For: 10.244.0.0
X-Forwarded-Host: kubeapps.example.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Scheme: http
origin: https://kubeapps.example.com
pragma: no-cache
cache-control: no-cache
sec-websocket-key: YW5jWwJFh8sQdqCj7XtYUg==
sec-websocket-version: 13
sec-websocket-extensions: x-webkit-deflate-frame
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
cookie: _oauth2_proxy=X29hdXRoMl9wcm94eS03OWZkNTk1MTcwOTY0MzIyZDhjMjVkNTc5NDNlMGY1NC4wWE9mMDM0N3BmNXRTT1VkcEpYNFJB|1630410142|999OjQYyNWzixv5sNRUirulaHip9SgniJrmpqXf8Bpg=
```

The result is an HTTP 101 - continue (which is good).

Then I tried this:
```
GET /api/clusters/default/apis/policy/v1beta1/undefined?watch=true&fieldSelector=metadata.name%3Dr2-grafana-test HTTP/1.1
Host: kubeapps.example.com
Connection: upgrade
Upgrade: websocket
X-Request-ID: b00b559b26c3e599e9541b16c55b7518
X-Real-IP: 10.244.0.0
X-Forwarded-For: 10.244.0.0
X-Forwarded-Host: kubeapps.example.com
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Scheme: http
origin: https://kubeapps.example.com
pragma: no-cache
cache-control: no-cache
sec-websocket-key: YW5jWwJFh8sQdqCj7XtYUg==
sec-websocket-version: 13
sec-websocket-extensions: x-webkit-deflate-frame
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
cookie: _oauth2_proxy=X29hdXRoMl9wcm94eS03OWZkNTk1MTcwOTY0MzIyZDhjMjVkNTc5NDNlMGY1NC4wWE9mMDM0N3BmNXRTT1VkcEpYNFJB|1630410142|999OjQYyNWzixv5sNRUirulaHip9SgniJrmpqXf8Bpg=
```

I get an HTTP 404 with a JSON message from the kube-apiserver saying the resource doesn't exist. This is also correct - it doesn't exist (and the nonexistence of the resource is related to bugs in other software unrelate to oauth2-proxy).

However, if I then _in the same telnet session_ paste the first message again, instead of HTTP 101, I get HTTP 403. Looking at the tcpdump traffic, I see the first request in the chain (the one generating the 404) includes the bearer token. However, the second one (generating the 403) does not - it's just a literal byte-for-byte forward of the message I pasted in to telnet.

If I disconnect and start another session, I can once again send that second message, and get a 101 again. Examining tcpdump shows that this time the headers are translated.

So either: The 404 should have set connection: close, or the second GET should have been examined by oauth2-proxy and rewritten, but it seems that it was forwarded on as if it were part of an active web socket stream.

Presumably this can be reproduced in an environment where you can get the upstream server to respond 404 to a web socket upgrade request and then access any other permitted resource in the same stream.

- Version used: oauth2-proxy v7.1.3 (built with go1.16.3)

### Edit:
Removing the `Connection: upgrade` from my 404-generating request makes the symptoms go away. This is obviously not a workaround since the downstream client _does_ want to try and get the connection upgraded, but this is why I suspect that the problem lies in pkg/upstream/http.go because of this line:
```
	if h.wsHandler != nil && strings.EqualFold(req.Header.Get("Connection"), "upgrade") && req.Header.Get("Upgrade") == "websocket" {
		h.wsHandler.ServeHTTP(rw, req)
	} else {
		h.handler.ServeHTTP(rw, req)
	}

```

### Edit:
Based on https://stackoverflow.com/questions/56999012/how-to-handle-error-using-newsinglehostreverseproxy it seems that you can set the ModifyResponse optional field and use a function to confirm that the status is OK, throwing an error if it's not. I'll see if I can get this working, and if so, provide a PR

### PR DESCRIPTION
**Pull request by thetrime**
…websocket proxying. This correctly handles 404 responses with keep-alive by terminating the tunnel rather than keeping it alive

## Description

httputil has handled websockets natively since go1.12. The upstream package yhat/wsutil hasn't been updated in years and fails to handle some edge cases

## Motivation and Context

This proposal fixes #1347 

## How Has This Been Tested?

The change is relatively localised. The way I tested it was as follows:
   1. I created a simple web server which echoed everything it received, and after receiving two newlines, wrote back this string: `HTTP/1.1 404 Not Found\nContent-Type: text/plain\nConnection: keep-alive\nContent-length: 7\n\nMissing`
   2. I tested the unpatched version of oauth2-proxy by opening a telnet session to it and pasting in a canned request twice. This request had the following features:
      * Upgrade: websocket
      * Connection: upgrade
      * Cookie: < a cookie corresponding to a valid oauth2-proxy session >
   3. The first request arrived at my test server with an Authorization: header. The second request did not.
   4. I then tested the patched version of oauth2-proxy in the same way
   5. The first request arrived at my test server with an Authorization: header. The second request did as well.

## Checklist:

- [X] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [X] I have created a feature (non-master) branch for my PR.

This should probably be mentioned in the changelog, but it shouldn't break anything that doesn't rely on what should be considered broken behaviour

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
Changes look reasonable to me, could you run a `go mod tidy` as I think it should probably remove the dependency from our dependency tree now.

Also please add a changelog. I'll try and find some time to take this for a test run before we merge if that's ok :slightly_smiling_face:

**Comment by NickMeves** [comment]
This is the one tricky area with websockets in particular that likely need a manual test:

https://github.com/oauth2-proxy/oauth2-proxy/blob/42475c28f7f235c08777a24027fe8ec170763482/pkg/middleware/request_logger.go#L81

If I recall, if this isn't working right, our access logs will drop authenticated user information (email & user fields in the logs). Eyeballing those in your manual tests might be a good final check.

**Comment by thetrime** [comment]
> Changes look reasonable to me, could you run a `go mod tidy` as I think it should probably remove the dependency from our dependency tree now.
> 
> Also please add a changelog. I'll try and find some time to take this for a test run before we merge if that's ok 🙂

No problem. As @NickMeves mentioned, this is quite hard to test in an automated way. It's certainly beyond the scope of my Go knowledge to set up and tear down the necessary HTTP servers. I have a test rig, but it's written in Prolog [don't ask].

The gist is that the server can respond with HTTP 404 to everything while logging all the headers it receives. If you try and do a websocket connection to the server twice, the first time you'll see the cookie translated into an authentication header, and the second time you won't.

**Comment by JoelSpeed** [comment]
Just trying to work out how to improve testing around this area and came across https://ieftimov.com/post/testing-in-go-websockets/, @thetrime I don't know if this is something you'd want to look into as a learning exercise? I know you said your Go knowledge isn't massive. If you don't want to delve to deep, I can look into extending the tests here to make sure we are covering this change at some point, let me know what you want to do

**Comment by thetrime** [comment]
> Just trying to work out how to improve testing around this area and came across https://ieftimov.com/post/testing-in-go-websockets/, @thetrime I don't know if this is something you'd want to look into as a learning exercise? I know you said your Go knowledge isn't massive. If you don't want to delve to deep, I can look into extending the tests here to make sure we are covering this change at some point, let me know what you want to do

Unfortunately I don't have time to do this now; realistically it'd probably be months before I could find time to sit down and teach myself another language. If you have the resources to implement a test framework, or can find someone else to do it, that'd definitely be the fastest road to getting it resolved

**Review by JoelSpeed — APPROVED** [review]
Had a chance to test drive this now, seems to be working as before, thanks @thetrime

**Pull request merged**
