### PR TITLE
docs/configuration: Fix entropy for bash secret

### PR DESCRIPTION
**Pull request by r4co0n**
Filtering `/dev/urandom` for alphanumeric characters resulted in loss of
input entropy to base64. Fixing this using a procedure with these steps:

  * Use `dd` to read 32 bytes from `/dev/urandom`
  * Concerting those to a single base64-encoded line
  * URL-Escaping the output
  * Appending a final newline

This output should be equivalent to output generated using Python and
OpenSSL variants mentioned in the changed document file.

Fixes: #1511

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
I tried to execute this on a mac and it doesn't work, that said, neither does the old version. 
```
dd if=/dev/urandom bs=32 count=1 status=none | base64 -w 0 | tr -- '+/' '-_'; echo
dd: unknown operand status
base64: invalid option -- w
Usage:	base64 [-hvDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
```

I wonder if there's a way we can make this Mac friendly. What is the `-w 0` option supposed to do in this function?

**Comment by JoelSpeed** [comment]
Have also just tested this on ubuntu and it seems to work OK and the proxy didn't blow up when I started it, so LGTM other than the above question

**Comment by r4co0n** [comment]
> I wonder if there's a way we can make this Mac friendly. What is the -w 0 option supposed to do in this function?

I have provided more information about this in the original issue report #1511:
> The -w 0 argument to base64 and the final ; echo can be omitted when dd's output encoded in Base64 does not exceed base64's line length. Leaving it in allows for arbitrarily big keys to be generated in one line as expected.

That said, we can surely find a way for this to work on MacOS as well, we will need to handle whitespace from `base64` manually.

**Comment by JoelSpeed** [comment]
Just had a quick play and I believe the following should work
```
dd if=/dev/urandom bs=32 count=1 2> /dev/null | base64 | tr -- '+/' '-_'
```

`status=none` doesn't work on the mac default `dd`, so instead `2> /dev/null` supresses the output nicely.
I dropped the `-w 0` which may or may not have issues, but there's no option like that on mac.

And I wasn't sure why we need an extra newline, this was giving me double new lines once I dropped the `-w 0` so I dropped the final echo

WDYT of this one?

**Comment by JoelSpeed** [comment]
Yep, that suggestion looks good! 

As for updates, if you want to have this in previous versions of the docs, then you should find a similar structure in each of the versioned docs folders and can update there, not 100% necessary though https://github.com/oauth2-proxy/oauth2-proxy/tree/master/docs/versioned_docs

As for changelog, I tend to think these are optional for docs changes, I use the changelog to identify changes that will affect the running product normally, that said, if you want to add a changelog, just add a line near the top (under changes since v7.2.1) and copy the existing format

**Comment by NickMeves** [comment]
> dd if=/dev/urandom bs=32 count=1 2> /dev/null | base64 | tr -- '+/' '-_'

This works for me too! I remember we had a PR a while ago related to this and my M1 Mac didn't support something in that PR that an older Intel Mac did 🤔

**Comment by r4co0n** [comment]
Thanks for guiding me along, I think we got something mergeable now.

@JoelSpeed, my question about a "documentation CHANGELOG" was misguided, I read the unticked checklist item saying:
> I have updated the documentation/CHANGELOG accordingly.

and thought there was a separate changelog in a subfolder, instead of understanding it as:
> I have updated the documentation and/or CHANGELOG accordingly.

Language is hard, but my question resulted in you pointing out the possibility to backport this to old documentation versions, which, though not necessary, I felt was easy enough to do and might help to avoid someone generating a less-than-ideal cookie secret.

While examining the versioned docs, I noticed that `version_7.1.x` for some reason uses only 16 instead of 32 bytes from `urandom` - I added a drive-by commit to make this 32 bytes in all versions. Let me know if this doesn't belong here.

Another thing which might be worth considering - It might make sense to replace `/dev/urandom` with `/dev/random` to make this block in the admittedly unlikely case that not enough entropy has been gathered when generating the cookie secret. Both the [Python](https://docs.python.org/3/library/os.html#os.urandom) and [OpenSSL](https://www.openssl.org/docs/man3.0/man1/openssl-rand.html) implementations behave this way already, I am not sure what Terraform and Powershell do.

**Review by JoelSpeed — APPROVED** [review]
Yep, this should be fine, the cookie secret code hasn't changed in a long time so the 32 bytes should be fine through all of these versions

**Comment by JoelSpeed** [comment]
> Another thing which might be worth considering - It might make sense to replace /dev/urandom with /dev/random to make this block in the admittedly unlikely case that not enough entropy has been gathered when generating the cookie secret. Both the [Python](https://docs.python.org/3/library/os.html#os.urandom) and [OpenSSL](https://www.openssl.org/docs/man3.0/man1/openssl-rand.html) implementations behave this way already, I am not sure what Terraform and Powershell do.

I don't really have a strong opinion on this, happy to merge as is, or have it updated, I don't actually have a sense on why it was `urandom` in the first place :thinking:

**Pull request merged**
