### PR TITLE
Add HealthCheck middleware

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

Adds healthchecking handler as a middleware

## Motivation and Context

Handle all healthchecking in one place. Allow testing of healthchecking separate from other components. Allow registering health check middleware before logging handler to implement silent logging.

## How Has This Been Tested?

Unit testing and manual testing using local testing environment

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

CC @chkohner @kskewes (I feel you may both have an interest in this)

### CODE REVIEW

**Comment by kskewes** [comment]
Nice, this is much cleaner. LGTM.

To remove the need for GCP specific code I guess we would need to make [`opts.PingPath`](https://github.com/oauth2-proxy/oauth2-proxy/blob/healthcheck-middleware/pkg/apis/options/options.go#L152) a slice of strings rather than a single string. That could always be done later if desired.

**Comment by JoelSpeed** [comment]
> To remove the need for GCP specific code I guess we would need to make opts.PingPath a slice of strings rather than a single string. That could always be done later if desired.

I had imaged we just deprecate the options and say to people that they will have to migrate their apps to use a single health/readiness endpoint, it shouldn't be very difficult I wouldn't have thought

**Comment by JoelSpeed** [comment]
Just did a bunch of manual testing of this and I'm happy that this is working as expected and retains all of the existing healthcheck behavour

**Comment by JoelSpeed** [comment]
Merging based on my own and @kskewes review, if anyone has any later comments I'll address those in a follow up

**Pull request merged**
