### PR TITLE
docs/conf/overview: Add hint about cookie prefixes to --cookie-name

### PR DESCRIPTION
**Pull request by Zocker1999NET**
## Description

Add a reference to the doc introducing users to cookie prefixes at the `--cookie-name` entry with a link explaining what advantages / disadvantages they bring with.

## Motivation and Context

Cookie Prefixes further restricts the possibilities of session attacks because supporting clients will only accept cookies with one of the prefix if certain requirements were meet, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#cookie_prefixes.

I found this security feature by chance and want to spread the word about it, and I think a reference in the docs of oauth2-proxy will improve the security of users of oauth2-proxy.

## How Has This Been Tested?

I use prefixes on my own. I can confirm that nothing essential breaks unexpectedly.

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.

Not so sure if the checklist applies to me.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
If you can add this into the unversioned docs so that it's included in the next release that would be helpful. +1 for spreading the word on security features where we can

**Comment by Zocker1999NET** [comment]
> If you can add this into the unversioned docs so that it's included in the next release that would be helpful. +1 for spreading the word on security features where we can

Where do I find the unversioned docs? Does this PR need to target another branch / repo?

**Comment by JoelSpeed** [comment]
They're in [docs/docs](https://github.com/oauth2-proxy/oauth2-proxy/tree/master/docs/docs) as opposed to `docs/versioned_docs`

**Comment by Zocker1999NET** [comment]
Okay, didn't saw the repo holds multiple versions in parallel. I migrated my commit to the unversioned version. May I add it to the older versions as well or are these considered immutable?

**Comment by JoelSpeed** [comment]
If you're happy to update the old docs then go ahead, it's helpful for the users on those older versions as well

**Comment by Zocker1999NET** [comment]
Okay, thanks. I rebased to the current master and backported the hint to the older docs. It should be ready to merge now.

**Pull request merged**
