### PR TITLE
Update go-redis/redis to v9.

### PR DESCRIPTION
**Pull request by arhamGH**
## Description

Update go-redis/redis to v9.
- And updated redislock, testify, ginko and gomega have also been updated.
- Renamed the option `IdleTimeout` to `ConnMaxIdleTime` because of https://github.com/go-redis/redis/blob/517938a6b083b8d4ffbc9d46c0bd9df19f10ffaf/CHANGELOG.md

## Motivation and Context

related  https://github.com/oauth2-proxy/oauth2-proxy/issues/1692

## How Has This Been Tested?

Tested it on Redis 7.x cluster
## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Does this affect our existing users? For example, does this mean they need to update to a new version of redis to be able to use this updated library?

**Review by JoelSpeed — APPROVED** [review]

**Comment by arhamGH** [comment]
> Does this affect our existing users? For example, does this mean they need to update to a new version of redis to be able to use this updated library?

Yeah according to the `go-redis` guys it should work https://github.com/go-redis/redis/discussions/2241#discussioncomment-3838212

**Review by JoelSpeed — APPROVED** [review]
Great, LGTM thanks

**Comment by JoelSpeed** [comment]
Looks like something failed because of the update to ginkgo, maybe we need to drop that dot import of the types since they created aliases now

**Review by JoelSpeed — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
