### PR TITLE
linkedidn: Update provider to v2

### PR DESCRIPTION
**Pull request by wuurrd**
## Description
Update the linkedin provider code to work with v2 of the API.

## Motivation and Context

Linkedin provider was no longer working

## How Has This Been Tested?

It is being used at https://try.ntropy.network - docker image built with this working: `wuurrd/oauth2-proxy` 
  

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Do you happen to have any reference that shows that the old APIs were deprecated and/or removed? Could you expand on why this is broken today?

If this is completely broken then we can accept this as a fix, but if it does still work then this would be considered a breaking change

**Comment by wuurrd** [comment]
I have no reference, but it is broken (getting 404 not found and similar)

**Comment by JoelSpeed** [comment]
This is probably a sufficient reference, they dropped support in May 2019, so we definitely need to update the provider
https://engineering.linkedin.com/blog/2018/12/developer-program-updates

**Comment by NickMeves** [comment]
> This is probably a sufficient reference, they dropped support in May 2019, so we definitely need to update the provider
> https://engineering.linkedin.com/blog/2018/12/developer-program-updates

Guess we had no users of this provider if it has been broken for 2 years 🤣 

I would say can we drop it, but @wuurrd being here with this PR is proof that they are a potential user 😄

**Comment by wuurrd** [comment]
It works with this PR, so it's probably worth keeping it?

**Review by JoelSpeed — DISMISSED** [review]
Yep, makes sense to me, please add a note to the changelog and I think I'm happy with this. Any additional thoughts from you @NickMeves ?

**Comment by JoelSpeed** [comment]
Might also be worth double checking our docs in case they have any specific references that need updating :thinking:

**Comment by NickMeves** [comment]
Good idea -- section is short: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#linkedin-auth-provider

@wuurrd Are those setup instructions still up to date or have things changed with LinkedIn?

**Comment by wuurrd** [comment]
@NickMeves only difference is 

`In default scope, select r_basicprofile and r_emailaddress.`

this should now say

`In default scope, select r_liteprofile and r_emailaddress.`

**Comment by wuurrd** [comment]
@JoelSpeed merge?

**Comment by NickMeves** [comment]
> @JoelSpeed merge?

We need a CHANGELOG entry added then we can merge 👍

**Comment by wuurrd** [comment]
@NickMeves can I leave this to you? I'm not sure where in the changelog you'd like that.

**Comment by JoelSpeed** [comment]
It should be under this section https://github.com/oauth2-proxy/oauth2-proxy/blob/master/CHANGELOG.md#changes-since-v713

**Comment by wuurrd** [comment]
@JoelSpeed this is ready for another review

**Review by JoelSpeed — APPROVED** [review]
LGTM, thanks @wuurrd

**Pull request merged**
