### PR TITLE
Add option to use Kubernetes ingress annotations to list valid emails

### PR DESCRIPTION
**Pull request by zv0n**
## Description

This change allows users to specify valid email addresses inside a Kubernetes Ingress annotation `oauth2-proxy.github.io/users`. If this feature is enabled, the validator searches all available ingresses. If an ingress with `host` equal to the request's host is found, its `users` annotation is compared with the email of the user who is trying to authenticate.

Multiple emails can be specified in the annotation, they must be separated by a comma.

## Motivation and Context

I have implemented this feature because in our company we want to use oauth2-proxy to communicate with an external identity provider and we want to use it for multiple sites (these sites are running in a Kubernetes environment). Each site has a different pool of users who are allowed to access it. We didn't want to have multiple instances of the proxy running just so we could specify different users, therefore this change was implemented to solve this problem.

## How Has This Been Tested?

- I have deployed the oauth2-proxy inside a Kubernetes environment with feature flag `--kubernetes-annotations`.
- I have deployed a few testing sites with the `oauth2-proxy.github.io/users` annotation containing emails of users who are allowed to access the site separated by commas (and of course the required annotations for auth redirect).
- I have then tried to access the sites as multiple users, only users specified in the annotations were allowed to access the site.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by braunsonm** [comment]
At first glace this seems like an odd proposal to me. `oauth2-proxy` is not (at least right now) a Kubernetes aware operator and the way you are providing the kube config seems non-standard. Are you actually setting a flag or environment variable in your `Deployment`? A service account should be created and used for this if we were to accept this. 

This kind of "per upstream" configuration seems better suited to the new configuration that is being worked on which will support multiple upstreams or make use of other ingress controllers in k8s that let you do various claim verification (like Istio) in conjunction with oauth2-proxy. This approach doesn't scale as there are limits in the size of Kubernetes annotations and the `Ingress` resource is not meant to handle authorization.

**Comment by NickMeves** [comment]
You might want to take a look at this PR/technique using ingress annotations that hook into a central Oauth2-Proxy via subrequests:

https://github.com/oauth2-proxy/oauth2-proxy/pull/849

And this underlying issue that describes the technique in detail: https://github.com/oauth2-proxy/oauth2-proxy/issues/831

Here's the K8s docs on this technique: https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

If you are proposing to extend how we use a central oauth2-proxy in different ways (allowed_groups, allowed_roles, email_domains, etc) you might want to take a look at that technique and extend that design pattern. This was recently extended to support `allowed_email_domains` for instance: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L1055

**Comment by zv0n** [comment]
Hi, @NickMeves 

I don't know exactly how the nginx ingress handles auth URLs, but wouldn't specyfing this kind of information in query string allow attackers to simply change it in their request? Or is the auth-url an internal call that is protected from such attacks?

**Comment by NickMeves** [comment]
> Hi, @NickMeves
> 
> I don't know exactly how the nginx ingress handles auth URLs, but wouldn't specyfing this kind of information in query string allow attackers to simply change it in their request? Or is the auth-url an internal call that is protected from such attacks?

Its a subrequest from nginx to OAuth2-Proxy -- so the querystring is fully controlled internally. The Auth endpoint returns 202 or 401(...? can't remember), then nginx continues the normal request to the backend.

**Pull request closed without merging**
