### PR TITLE
support go get installation

### LINKED ISSUE #740: go get github.com/oauth2-proxy/oauth2-proxy seem to install outdated version, maybe v3.2.0?
## Expected Behavior

the go get command should build the latest stable/secure release. (or at least I think so)

## Current Behavior

Running 

`GO111MODULE=on go get github.com/oauth2-proxy/oauth2-proxy`

builds an executable in /home/user/go/bin/oauth2-proxy that appears to be an outdated version. 

## Possible Solution

I'm not knowledgeable on the go build system, so I don't know.

## Steps to Reproduce (for bugs)

1. run GO111MODULE=on go get github.com/oauth2-proxy/oauth2-proxy 
2. Check if the output of /home/user/go/bin/oauth2-proxy --help  is as expected  (--version just says undefined)

## Context

I used the automated go get build process in a container, but the resulting executable doesn't behave like the docs describe. For instance, it doesn't have the --banner option as is described in the docs.  I also get the same behavior when running the go get command directly on my archlinux system.

## Your Environment
$ go version
go1.15 linux/amd64

$ uname -a
Linux archlinux 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

### PR DESCRIPTION
**Pull request by johejo**
## Description

Properly use the go module to support go get installation.
v6 is added to the import path.

## Motivation and Context

close #740

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
I'd like to have some discussion about whether this is actually something we want to support or not.

It's not as bad as I had first thought, though my general thoughts on this are that typically, this kind of go get is used to install libraries. As an application, maybe we shouldn't be supporting go modules in this way?

Was this mostly a find and replace to create this PR? Do you think it would be a lot of effort to create the next version?

Do we consider this a breaking change? Technically I don't think so, but in terms of go modules it should be 😓

**Comment by johejo** [comment]
Thank you for your very valuable comment.
Most users will try a binary installation.
The `go get` should be very rare.
But It's also true that installing tools made by Go with the `go get` is a relatively well known method.

There are other perspectives as well.
However, some people may find oauth2-proxy on pkg.go.dev etc.
At this time, the user cannot see the latest version. There are no v6 characters on the pkg.go.dev page.
But most users don't have to read godoc because oauth2-proxy is not a library, and oauth2-proxy developers don't actively write godoc now.

**Comment by johejo** [comment]
I did most of my work in simple replacement.
```
find ./ -name "*.go" | xargs sed -i -e's|"github.com/oauth2-proxy/oauth2-proxy"|"github.com/oauth2-proxy/oauth2-proxy/v6"|'
```

I searched some case studies about tools written in Go.

go module with major version prefix
- [golang-migrate/migrate](https://github.com/golang-migrate/migrate)
- [go-acme/lego](https://github.com/go-acme/lego)
- [containous/traefik](https://github.com/containous/traefik)
- [caddyserver/caddy](https://github.com/caddyserver/caddy)

go module without major version prefix
- [cockroachdb/cockroach](https://github.com/cockroachdb/cockroach)
- [prometheus/prometheus](https://github.com/prometheus/prometheus)
- [goharbor/harbor](https://github.com/goharbor/harbor)
- [pingcap/tidb](https://github.com/pingcap/tidb)
- [vitessio/vitess](https://github.com/vitessio/vitess)

The difference between them seems to be whether they are designed only as tools (servers) or have the functionality of being embeddable libraries.
oauth2-proxy will be close to the latter. 
This PR may decline.

**Comment by JoelSpeed** [comment]
@johejo I think we should be doing this, but we will need to bump to v7 as part of this. We are planning to do a breaking release in the near future so if you could reopen and update to v7 then we can get this in the queue to merge, WDYT?

**Comment by JoelSpeed** [comment]
@johejo Could you reopen this PR, update it to `v7` instead of `v6`, and then I'm happy to get this merged 😄

**Comment by johejo** [comment]
Thanks, I plan to retry.

**Pull request closed without merging**
