### PR TITLE
Bugfix/check json path

### PR DESCRIPTION
**Pull request by eloo-abi**
## Description

Add a small check for jsonpath before splitting and interpreting a claim string as jsonpath.
This is improving the jsonpath handling for claims and also will fix the usage of custom claims in webdomain format like mentioned here: https://github.com/oauth2-proxy/oauth2-proxy/issues/1730

## Motivation and Context

Not every string with a period is a valid jsonpath and thus should not interpreted as such one.

## How Has This Been Tested?

Manually tested

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG. -> no
- [x] I have updated the documentation/CHANGELOG accordingly. -> no
- [x] I have created a feature (non-master) branch for my PR. -> yes

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
Can you provide some examples of something that might fail this parsing?

**Comment by eloo** [comment]
Please check my comment here
https://github.com/oauth2-proxy/oauth2-proxy/issues/1730#issuecomment-1364344348

**Comment by eloo-abi** [comment]
not stale

**Comment by eloo-abi** [comment]
@JoelSpeed can may have a look here?

**Comment by JoelSpeed** [comment]
Please add a changelog entry for this and update against the latest master branch. I think in general the change should be ok given the existing library should already take into account paths within the JSON structure.

I'd like to see some tests added for cases that pass with this new logic that do not pass for the old logic before we merge please

**Comment by eloo-abi** [comment]
@JoelSpeed test added and changelog is updated

**Comment by mruoss** [comment]
@JoelSpeed any chance to get this reviewed/merged? Thanks a lot.

**Comment by tuunit** [comment]
@JoelSpeed Rechecked the code and tests. LGTM. Can be merged.

**Comment by eloo-abi** [comment]
thanks :) 
hope to see this released in the next version

**Pull request merged**
