### PR TITLE
GKE Workload Identity support

### LINKED ISSUE #1808: Support for GKE workload identities with Google auth
## Current Behavior

I have an authentication setup using Google Groups in GKE, but I get the following error.
```
[2022/10/03 09:26:47] [main.go:54] invalid configuration:
  missing setting: google-service-account-json
```
I would like to use GKE WorkloadIdntity to set up authentication for Google Groups without issuing JSON keys for service accounts, is this not supported?

## Possible Solution

It would be nice to support GKE workload identities and be able to start without the `google-service-account-json` flag.
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

## Your Environment

- Version used: 7.2.1

### PR DESCRIPTION
**Pull request by kvanzuijlen**
## Description
This PR will enable Workload Identity (on GKE)/Application Default Credentials support for the Google Provider.

The workspace admin account needs to have the `iam.serviceAccounts.signJwt` permission (i.e. `roles/iam.serviceAccountTokenCreator`) (does this need to be added to the docs?). This PR also adds 2 new flags; `--google-use-application-default-credentials` and `--google-target-principal`.  The last one is in my understanding used to impersonate the correct Google Service Account using the Kubernetes Service Account.

## Motivation and Context

closes #1808

## How Has This Been Tested?

Integration-tested by building a test image and deploying to a Kubernetes cluster in combination with Nginx OAuth annotations. Tested it with and without allowed_groups.
Also tested it on localhost with an Nginx reverse proxy with self-signed certs for SSL using application default credentials (using `gcloud auth application-default login`).

Not yet tested on GCE/Anthos

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by kvanzuijlen** [comment]
Please let me know if the codeclimate issues need fixing and if there's anything else I should do to get this PR merged.

**Comment by pierluigilenoci** [comment]
@JoelSpeed @NickMeves could you please take a look?

**Comment by swarupdonepudi** [comment]
thanks for the help @kvanzuijlen . I am looking forward to this feature. I would like to also contribute if needed either to get this pr going to with other features on this project.

**Comment by kvanzuijlen** [comment]
@JoelSpeed Could you please take a look at this since the necessary changes have already been added to the Helm chart? See https://github.com/oauth2-proxy/manifests/pull/127

**Pull request closed without merging**
