### PR TITLE
Add ValidateSession function to LoginGovProvder to include Auth Header

### PR DESCRIPTION
**Pull request by pksheldon4**
## Description

Add ValidateSession function to LoginGovProvider to include Authorization header using access_token

## Motivation and Context
This recent bug fix is causing Login.gov oauth to fail "[#1433](https://github.com/oauth2-proxy/oauth2-proxy/pull/1433) Let authentication fail when session validation fails (@stippi2)"
We need to be able to update as this and future versions to resolve new CVE's.

## How Has This Been Tested?

I've tested this locally running the module and in our K8s test cluster to ensure it to work.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x ] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Seems reasonable, would you be able to add a changelog entry and then we can get this merged

**Comment by pksheldon4** [comment]
> Seems reasonable, would you be able to add a changelog entry and then we can get this merged

Done. Newish to this so please let me know if you need anything else from me.

**Review by stippi2 — APPROVED** [review]
Looks reasonable.

**Comment by pksheldon4** [comment]
Just checking in to see if this is waiting on anything from me ? Or what the cadence is for new releases ?

**Review by JoelSpeed — DISMISSED** [review]
Sorry for the delay, very busy at the moment so not getting much time to look at the project

**Comment by pksheldon4** [comment]
> Sorry for the delay, very busy at the moment so not getting much time to look at the project

I understand. Just wanted to make sure my lack of understanding wasn't delaying things.  I don't see any errors in the build, except for the Failed at the very end. I'm not sure how to proceed.

**Comment by JoelSpeed** [comment]
One of the tests looks like it'll need an update
https://github.com/oauth2-proxy/oauth2-proxy/runs/5054354303?check_suite_focus=true#step:8:1352

**Comment by pksheldon4** [comment]
> 



> One of the tests looks like it'll need an update https://github.com/oauth2-proxy/oauth2-proxy/runs/5054354303?check_suite_focus=true#step:8:1352

I'm trying to understand the error as it's not obvious from the logs.  I also tried running the tests on the latest code https://github.com/oauth2-proxy/oauth2-proxy/ using `make test` and I get the same error.

**Comment by JoelSpeed** [comment]
The failure, just to confirm is:
```
=== RUN   TestNewLoginGovProvider
    logingov_test.go:78: 
        Expected
            <string>: https://secure.login.gov/api/openid_connect/userinfo
        to equal
            <string>: 
--- FAIL: TestNewLoginGovProvider (0.00s)
```
I'm not seeing this error when I run against the master branch. The test is related to how the logingov provider is configured so it seems like it could be linked to this PR

**Comment by JoelSpeed** [comment]
Seems to me like we need to update this test case with the new validate URL
https://github.com/oauth2-proxy/oauth2-proxy/blob/4f5efd4074098223aeee244b963dafa9cfd4924b/providers/logingov_test.go#L78

**Comment by pksheldon4** [comment]
> The failure, just to confirm is:
> 
> ```
> === RUN   TestNewLoginGovProvider
>     logingov_test.go:78: 
>         Expected
>             <string>: https://secure.login.gov/api/openid_connect/userinfo
>         to equal
>             <string>: 
> --- FAIL: TestNewLoginGovProvider (0.00s)
> ```
> 
> I'm not seeing this error when I run against the master branch. The test is related to how the logingov provider is configured so it seems like it could be linked to this PR

Yes, this is definitely on me. Still getting used to how to test this project.  If I just run `make test` or even `./.github/workflows/test.sh` that test doesn't seem to run.

**Review by JoelSpeed — APPROVED** [review]
I think this should be good now, thanks!

**Pull request merged**
