### PR TITLE
Add option api-path-regex

### LINKED ISSUE #551: Different handling of UI paths and API paths on unauthorized requests
I've seen https://github.com/oauth2-proxy/oauth2-proxy/issues/461 but I think this is worth discussing further.

If a SPA is open in the browser and the user manages to idle out or logs out of the auth provider (so access and/or refresh token are not valid anymore), a HTTP request to backend API of the application should result in a 403, so the SPA can handle (e.g. with a page refresh).

## Expected Behavior

- If Auth Cookie is deleted:
- API request returns 403

## Current Behavior

- If Auth Cookie is deleted:
- API request returns 302 with redirect to authorization endpoint of the auth provider

## Possible Solution

Like with the `skip_auth_regex` configuration a `skip_redirect_regex` (or some other possibly more meaningful `api_regex`) configuration can be added. If the request is not authorized and matches this regex, don't redirect to auth provider but return a 403 instead.

I'm happy to prepare a PR btw ;)

### PR DESCRIPTION
**Pull request by segfault16**
Paths that match any regex return http status 401 instead of redirecting to authorization endpoint.

This resolves #551 

## Description
This PR adds a configuration item that allows to specify API paths via multiple regex.

## Motivation and Context
The current check if an unauthorized request should trigger a redirect to the login page / authorization endpoint covers AJAX requests only, other protocols like GRPC are not covered by this implementation.
The proposed solution allows configuration of API paths regardless of the used protocol.
See issue #551 

## How Has This Been Tested?

See code and tests, made the change as non-intrusive as possible

Before:
Screen Shot 2020-05-14 at 06 50 28
-> All API requests are redirected to authorization endpoint

After:
Screen Shot 2020-05-14 at 06 51 44
-> All API requests return 401 which can be handled by frontend

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

Added documentation of the configuration option, didn't change CHANGELOG though.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@segfault16 I think this issue is worth fixing, please see my comment on the issue you raise https://github.com/oauth2-proxy/oauth2-proxy/issues/551#issuecomment-629776251

**Comment by p53** [comment]
is there any update for this?

**Comment by louisgls** [comment]
any update ?

**Comment by zhangjinxu** [comment]
any update ?

**Comment by segfault16** [comment]
new PR: #1760

**Pull request closed without merging**
