### PR TITLE
documented default for errors-to-info-log

### PR DESCRIPTION
**Pull request by anotherthomas**
The default for errors-to-info-log isn't documented 

## Description

The default for errors-to-info-log was not documented. Since that option can be really helpful analyzing issues, I have added it to the docs.

## Motivation and Context

More complete documentation.

## How Has This Been Tested?

Just a documentation update.

## Checklist:
- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Review by JoelSpeed — DISMISSED** [review]
LGTM, thanks for fixing this up

**Comment by anotherthomas** [comment]
I've rebased the branch

**Comment by anotherthomas** [comment]
Anything else needed from my side?

**Comment by anotherthomas** [comment]
Any way I can help?

**Comment by tuunit** [comment]
@anotherthomas sorry for the delay. Could you do a rebase of your branch once more. After that we can merge it.

CC: @JoelSpeed can be merged.

**Comment by anotherthomas** [comment]
> @anotherthomas sorry for the delay. Could you do a rebase of your branch once more. After that we can merge it.
> 
> CC: @JoelSpeed LGTM.

No problem

**Review by tuunit — APPROVED** [review]

**Review by JoelSpeed — APPROVED** [review]

**Pull request merged**
