### PR TITLE
Fix docker build/push issues found during last release

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

This updates the docker build and push process to rely solely on the buildx command for consistency and drops the old dockerfiles for cross building as we no longer need to maintain these.

## Motivation and Context

While performing release v7.2.0, I found issues trying to push the images and as such, had to add some hacks in to get it to push. I've now fixed this and tested locally.

## How Has This Been Tested?

Ran `make docker-all docker-push-all` against my own registry, pulled the various platform images down, copied the oauth2-proxy binary from them and checked their build architecture using `file`

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by jkandasa** [comment]
@JoelSpeed I think we can stop building `*-amd64`, `*-arm64`, `*-armv6` separately 
Those are available in `DOCKER_BUILD_PLATFORM ?= linux/amd64,linux/arm64,linux/arm/v6`

**Comment by JoelSpeed** [comment]
I've left those in as separate items for now to make sure we do still keep building them and retain the old tags for a couple of releases at least.

When building/pushing this it does realise that they've already been built and effectively justs adds a new tag to the existing image, so I don't think there's any harm in having them there as they are now.

**Comment by jkandasa** [comment]
@JoelSpeed +1

**Review by NickMeves — DISMISSED** [review]
LGTM! Thanks for fixing this up.

**Pull request merged**
