### PR TITLE
Let authentication fail when session validation fails (fixes #1396)

### LINKED ISSUE #1396: Result of provider.ValidateSession() is ignored during session creation
## Expected Behavior

Authentication fails if the JWT validation fails.

## Current Behavior

The result of the JWT validation does not have any effect, as the return value of the function [is ignored](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L756).

## Possible Solution

Look at the return value and fail authentication if necessary.

## Steps to Reproduce (for bugs)

For debugging purposes, I have configured a really short token expiry time in the OIDC issuer (1 minute). I have stepped through the code for authentication flow after the oauth2/callback endpoint is called, i.e. when initiating the fresh session. This caused enough of a delay that the token was already expired before it was being validated. The validation failed as expected [here](https://github.com/coreos/go-oidc/blob/v3/oidc/verify.go#L271). But then I realized that the result of `ValidateSession()` is actually ignored. I assume token expiry is not the only reason why validation can fail.

## Your Environment

- Version used:

https://github.com/oauth2-proxy/oauth2-proxy/commit/fd5e23e1c55ec99f552321a317770015a4b788e1

### PR DESCRIPTION
**Pull request by stippi2**
## Description

Use the result of `provider.ValidateSession()` to display an error page and return a 403 if necessary.
Fix the existing test cases for OAuth2Proxy and add another test case asserting a failing validation results in a 403.

## Motivation and Context

See [original issue](https://github.com/oauth2-proxy/oauth2-proxy/issues/1396) for context and more details.

## How Has This Been Tested?

Test coverage is provided as well as changes for tests that relied on the previous behavior and while using the default value of `TestProvider.ValidToken`. These tests now set this value to `true` before running.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Review by NickMeves — DISMISSED** [review]
Looks great! Great tests!

If you could go ahead and add a CHANGELOG entry, this looks good to go to me 👍

**Comment by stippi2** [comment]
Not sure if you get the notification for commit activity. I've added the CHANGELOG entry. Can you please approve again?

**Comment by stippi2** [comment]
This PR was already approved. "I" dismissed the review by following up on the review comment to include a changelog entry. Can you please re-approve?

**Review by JoelSpeed — APPROVED** [review]
Thanks for the fix!

**Comment by pierluigilenoci** [comment]
@JoelSpeed @NickMeves when is a release planned? I need this fix.

**Comment by JoelSpeed** [comment]
There are a couple of small bug fixes that we need to get in, once they are merged we will get a new release out

**Pull request merged**
