### PR TITLE
TOTVS provider

### PR DESCRIPTION
**Pull request by felipeconti**
A new TOTVS provider

## Description

[TOTVS](https://www.totvs.com) is a big tech company from Brazil, and this provider will enable customers to use it with oauth2-proxy.

## Motivation and Context

The motivation behind that is related to authenticate APIs and/or services using TOTVS Identity by default.

## How Has This Been Tested?

Default testing.

## Checklist:

- [X] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
I'm hesitant to add new providers right now as we are planning a large rewrite of this area of the code. Which provider is this based on and how different is it from that?

Why can the generic provider not be used here?

**Comment by felipeconti** [comment]
Really I need a generic oauth2 provider instead, that is the diference form others provider here.

There is a plan in your large rewrite to build a generic oauth2 provider?

**Comment by felipeconti** [comment]
> Really I need a generic oauth2 provider instead, that is the diference form others provider here.
> 
> There is a plan in your large rewrite to build a generic oauth2 provider?

@JoelSpeed ?

**Comment by JoelSpeed** [comment]
Apologies, not getting a lot of time to get to this project right now. 
> Really I need a generic oauth2 provider instead, that is the diference form others provider here.
>
> There is a plan in your large rewrite to build a generic oauth2 provider?

Yes, I was thinking this. One of the projects I'd like to see happen is to create a new generic OAuth2 provider and a new generic OIDC provider, that are very customisable through config to allow things like this. I'm hesitant to accept new providers that are very specific at the moment until that work is done.

**Pull request closed without merging**
