### PR TITLE
Update golang.org/x/net to v0.7.0 ato address GHSA-vvpx-j8f3-3w6h

### PR DESCRIPTION
**Pull request by amrmahdi**
## Description

Addresses https://github.com/advisories/GHSA-vvpx-j8f3-3w6h

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Review by Michael-Sinz — DISMISSED** [review]

**Review by JoelSpeed — COMMENTED** [review]
Could you please add a changelog entry and we can get this merged, thanks!

**Comment by amrmahdi** [comment]
> Could you please add a changelog entry and we can get this merged, thanks!

Done.

**Review by JoelSpeed — APPROVED** [review]

**Comment by amrmahdi** [comment]
Thanks @JoelSpeed, is there a timeline when a new version with this update will be released?

**Comment by segaura** [comment]
> Thanks @JoelSpeed, is there a timeline when a new version with this update will be released?

Just a note if it can be useful...
Looking at oauth2-proxy code, the `x/net` module is present only to include `x/net/websocket` in two _test files_: `upstream_suite_test.go` and `http_test.go`.
If I am right and I understand enough the build process, I expect no `x/net` components to be present in final executable.
I noticed this because some of our company vulnerability detection software (e.g. Dependency Track) does not report `x/net` as an effective dependency.

**Comment by amrmahdi** [comment]
> > Thanks @JoelSpeed, is there a timeline when a new version with this update will be released?
> 
> Just a note if it can be useful... Looking at oauth2-proxy code, the `x/net` module is present only to include `x/net/websocket` in two _test files_: `upstream_suite_test.go` and `http_test.go`. If I am right and I understand enough the build process, I expect no `x/net` components to be present in final executable. I noticed this because some of our company vulnerability detection software (e.g. Dependency Track) does not report `x/net` as an effective dependency.

Which version are you using? It is definitely in 7.3.0 and 7.4.0:

### 7.3.0

```bash
$ go version -m oauth2-proxy | grep net
        dep     golang.org/x/net        v0.0.0-20211112202133-69e39bad7dc2      h1:CIJ76btIcR3eFI5EgSo6k1qKw9KJexJuRLI9G7Hp5wE=
```

### 7.4.0

```bash
$ go version -m oauth2-proxy | grep net
        dep     golang.org/x/net        v0.1.0  h1:hZ/3BUoy5aId7sCpA/Tc5lt8DkFgdVS2onTpJsZ/fl0=
```

**Comment by segaura** [comment]
My ingenuousness.
I looked only in source code, and it is true that only two go source files use `x/net` as a _direct dependency_.
You are right, `x/net` is present anyway in the final builds because it is also a _transitive dependency_ (imported by `gomega`, `transport`, `grpc`, the dependency graph below generated from current master branch shows no `x/net/websocket` usage, indeed).
I will investigate further on why Dependency Track does not report that vulnerability, thank you for you patience.

graph

**Pull request merged**
