### PR TITLE
adding IdleTimeout with the redis-connection-idle-timeout flag, to ke…

### PR DESCRIPTION
**Pull request by Dimss**
If Reids option `timeout` is set to non-zero value, `oauth2-proxy` will failed to load or save sessions due to 
default `IdleTimeout` 0 configuration 
## Expected Behavior
when user has redis with `timeout` option, `oauth2-proxy` should provide an configuration option to set the `IdleTimeout` to desired value 

## Current Behavior
Currently there is no way to specify `IdleTimeout` for Redis connections

## Possible Solution
PR with the fix has been opened 

## Steps to Reproduce (for bugs)

1. create redis and set `timeout` option to 15 sec
2. start the `oauth2-proxy` 

after first 15 seconds, proxy will fail to load the session from Redis with error:
`Error loading cookied session: failed to load the session state with the ticket: error loading redis session: EOF, removing session`

- Version used:
v7.3.0

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
This seems reasonable, can you make sure to add the relevant documentation to the configuration docs.

Is there any way we can add any tests for this that you've looked into?

**Comment by Dimss** [comment]
@JoelSpeed I've added the configuration docs with includes explanations, link to the Redis configuration, and the configuration example. 

Regarding the tests, the `redis_store_test.go` is based on the [miniredis](github.com/alicebob/miniredis) which does not supports the [Redis timeout option](https://redis.io/docs/reference/clients/#client-timeouts). 
So, creating a test for that specific edge-case, won't be probably possible without integrating real Redis instances within the tests infra.

In addition, this is somehow more Go TCP implementation, so maybe it is not necessary should be covered here.

**Review by JoelSpeed — DISMISSED** [review]
Looks good, thanks!

**Comment by JoelSpeed** [comment]
Please add a changelog entry and I'll get this merged

**Comment by Dimss** [comment]
@JoelSpeed done, the changelog has been updated, thank you.

**Review by JoelSpeed — APPROVED** [review]

**Pull request merged**
