### PR TITLE
Discord Provider

### PR DESCRIPTION
**Pull request by l1n**
## Description

Added provider for [Discord](https://discord.com).

## Motivation and Context

This provider expands the capabilities of this program and I'd like to move to using upstream's version of the package rather than patching it myself each time you upgrade.

## How Has This Been Tested?

I run this in production in front of a website that uses Discord login.

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR. (I mean, it's in a fork, I think so)

### CODE REVIEW

**Comment by l1n** [comment]
All I'm so sorry I didn't realize how much linting y'all did before trying to push this upstream, I'll convert back to a regular PR once builds are happy

**Comment by NickMeves** [comment]
Before you spend to much time on this, please take a look at this old issue (we just unpinned it recently): https://github.com/oauth2-proxy/oauth2-proxy/issues/429

We are actually thinking about reducing the number of providers we support and culling some of the less popular ones. As we redesign the software and add new features, the implementation time goes up dramatically if we have to deal with refactoring in all the providers we support.

For that reason we are very hesitant to add new providers at this point unless there is widespread demand in the community for a major provider we are lacking.

**Comment by l1n** [comment]
429 appears to be stale and was opened in March - is there currently progress on said generic interface? I guess I can continue running my fork, but it seems kind of silly given that provider implementation as I understand it is a fairly straightforward process and I'm happy to maintain this provider in perpetuity (since I use it).

**Comment by NickMeves** [comment]
> I'm happy to maintain this provider in perpetuity (since I use it).

Famous last words of the `login.gov`, `nextcloud` & `digitalocean` contributors 🤣 

If you continue to work on this, the `GetUserName` and `GetEmailAddress` post-Redeem helpers were deprecated in favor of  the `EnrichSessionState` method recently. This is now where you can do all post `Redeem` calls to the IdP to get extra data.

When you add unit tests, we are migrating everything to `Ginkgo` where possible. It doesn't look to be in the `provider` package yet, but this PR is an example of another provider taking the plunge and converting unit tests to the new preferred library: https://github.com/oauth2-proxy/oauth2-proxy/pull/630/files

**Comment by NickMeves** [comment]
I'm going to close this for now. We don't intend to support new Providers at the moment.

**Comment by ronaldmiranda** [comment]
+1

**Pull request closed without merging**
