### PR TITLE
Move static content to oauth2-proxy-static to avoid name collisions (#2223)

### LINKED ISSUE #2223: 7.5.0 breaks protected path /static, HTTP 404
## Expected Behaviour

Protected resource can still host on /static, just like in 7.4.0

## Current Behaviour

404 page not found on resources hosted on /static
Caused by https://github.com/oauth2-proxy/oauth2-proxy/pull/2025

## Possible Solution

Rolling back to 7.4.0

## Steps to Reproduce (for bugs)

Host a resource that has content on /static, for example jupyter
login to the oauth proxy

the page does not fully load, requests to /static get a 404 response

calling the proxy on port 8080
```
kubectl debug -n tools -it jupyterlab-98c75c5c8-8qxq8  --image=curlimages/curl -- curl "http://localhost:8080/jupyter/static/lab/main.bcccfe17b7cd76ace990.js?v=bcccfe17b7cd76ace990"
Defaulting debug container name to debugger-rtpwv.
404 page not found
```

calling the underlying service on port 8888
```
kubectl debug -n tools -it jupyterlab-98c75c5c8-8qxq8  --image=curlimages/curl -- curl "http://localhost:8888/jupyter/static/lab/main.bcccfe17b7cd76ace990.js?v=bcccfe17b7cd76ace990"
Defaulting debug container name to debugger-rtpwv.
(()=>... (a valid response)
```

## Context

Will roll back for now

## Your Environment

```yml
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.0
          ports:
            - containerPort: 8080
          args:
            - "--upstream=http://localhost:8888"
            - "--banner=-"
            - "--footer=-"
            - "--custom-sign-in-logo=-"
            - "--cookie-secure=true"
            - "--cookie-expire=8h0m"
            - "--cookie-refresh=60m"
            - "--cookie-domain=censored.de"
            - "--http-address=0.0.0.0:8080"
            - "--proxy-prefix=/jupyter"
            - "--redirect-url=https://censored.de/jupyter/callback"
            - "--email-domain=censored.de"
            - "--provider=oidc"
            - "--client-id=123456"
            - "--oidc-issuer-url=https://login.microsoftonline.com/987645/v2.0"
```

- Version used: 7.5.0, 7.5.1

### PR DESCRIPTION
**Pull request by StefanLobbenmeierObjego**
## Description

Renamed the static folder to oauth2-proxy-static, so that content hosted by underlying application on /static can still be accessed.

## Motivation and Context

Jupyter hosts resources on /static
Closes #2223

## How Has This Been Tested?

Tested locally against the configuration that I use in production. Basically like this:

Built it like this:
```bash
GOROOT=/opt/homebrew/opt/go/libexec #gosetup
GOPATH=/Users/lobbenst/go #gosetup
/opt/homebrew/opt/go/libexec/bin/go build -o /Users/lobbenst/Library/Caches/JetBrains/IntelliJIdea2023.3/tmp/GoLand/___1go_build_github_com_oauth2_proxy_oauth2_proxy_v7 github.com/oauth2-proxy/oauth2-proxy/v7 #gosetup
```

ran it like this:
```bash
OAUTH2_PROXY_CLIENT_SECRET=censored \
OAUTH2_PROXY_COOKIE_SECRET=censored \
/Users/lobbenst/Library/Caches/JetBrains/IntelliJIdea2023.3/tmp/GoLand/___1go_build_github_com_oauth2_proxy_oauth2_proxy_v7  \
"--upstream=http://localhost:8888/" \
"--banner=-" \
"--footer=-" \
"--custom-sign-in-logo=-" \
"--cookie-secure=true" \
"--cookie-expire=8h0m" \
"--cookie-refresh=60m" \
"--cookie-domain=censored.de" \
"--http-address=0.0.0.0:8080" \
"--proxy-prefix=/jupyter" \
"--redirect-url=https://censored.de/jupyter/callback" \
"--email-domain=censored.de" \
"--provider=oidc" \
"--client-id=123456" \
"--oidc-issuer-url=https://login.microsoftonline.com/987645/v2.0" 
```

And for my local testing I had to add some more settings:
"--tls-cert-file=mycert.crt" \
"--tls-key-file=mycert.key" \

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.
- [ ] I have written tests for my code changes.

### CODE REVIEW

**Review by tuunit — APPROVED** [review]

**Comment by JoelSpeed** [comment]
I disagree with this change and I think you're using `--proxy-prefix` wrong.

The intention of the proxy-prefix flag is to allow you to set a unique path so that there isn't any overlap. In your case, I suspect you want to set the prefix to `/jupyter/oauth2`, that is, assuming there's no path within Jupyter that relies on `oauth2` being a sub path.

**Comment by tuunit** [comment]
Hi @StefanLobbenmeierObjego,

could you please test if the `--proxy-prefix=/jupyter/oauth2` suggested by @JoelSpeed solves your issue?

**Comment by StefanLobbenmeierObjego** [comment]
Hi - thanks for the feedback. I will try it out, waiting for permissions to add that redirect uri in azure, but I will let you know

**Comment by StefanLobbenmeierObjego** [comment]
That worked, thank you very much for the support ❤️  I will also let the other affected person know in the linked issue

**Pull request closed without merging**
