### PR TITLE
Fixed regex for detecting JWTs (#2794)

### PR DESCRIPTION
**Pull request by soskamp**
The regex for detecting JWTs in an HTTP header assumed that it must start with "ey" followed by an "I" or "J". This assumes there is no whitespace in the JWT (before base64 encoding). However, RFC7159 does allow for whitespace in JWTs.

## Motivation and Context

Fix for #2794 

Given that OAuth2 Proxy has no debug logging it is very hard to find out that it actually did not consider a JWT just because it starts with "ew" (base64) and not "ey". Only after studying the source code, it dawned on me that the JWT was simply ignored without further notice.

It usually is no problem to generate JWTs that match OAuth2 Proxy's expectation, but without knowing what is expected, it is impossible.

## How Has This Been Tested?

I compiled my own version of oauth2-proxy and that worked with the unusual JWT.

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.
- [ ] I have written tests for my code changes.
- [X] Fix affects a single line of code.

Edit: Typos.

### CODE REVIEW

**Review by tuunit — CHANGES_REQUESTED** [review]
Thanks for raising this PR but instead of being less strict with the regex match. I would prefer we add a log line for the case you described.

I don't fully agree that RFC 7519 allows for whitespaces before the JWT object itself.

According to https://datatracker.ietf.org/doc/html/rfc7519#section-3:

> ..., the JSON object consists of
   zero or more name/value pairs (or members), where the names are
   strings and the values are arbitrary JSON values.  These members are
   the claims represented by the JWT.  This JSON object MAY contain
   whitespace and/or line breaks before or after any JSON values or
   structural characters, in accordance with [Section 2 of RFC 7159](https://datatracker.ietf.org/doc/html/rfc7159#section-2)
   [[RFC7159](https://datatracker.ietf.org/doc/html/rfc7159)].

It allows for whitespaces and line breaks inside the object but not in front or after the JSON curly braces itself. And even if the part `or structural characters` could be interpreted like that. I really don't like the idea of being less strict. I've yet to see any service sends JWTs containing unnecessary whitespaces.

**Comment by soskamp** [comment]
Thanks for the review, @tuunit. I agree, we should stick to the RFC. However, the statement, "This JSON object MAY contain
whitespace and/or line breaks before or after any JSON values or structural characters[...]", in RFC7519 means leading whitespace is just part of the JSON object, because the opening "{" is just a _structural character_. RFC7159 is less ambiguous in this respect.

RFC7519 has an example in section 3.1 and explains, "In the representation used in this example, the first line has no leading or trailing spaces", but that does not forbid leading spaces.

I also like the fact that JWTs usually start with "ey", but the RFCs do not mandate this.

**Comment by tuunit** [comment]
Unfortunately, the RFC isn't clear at all about this in [7.2.](https://datatracker.ietf.org/doc/html/rfc7519#section-7.2) it explicitly mentions that during the validation of the header whitespaces and linebreaks aren't allowed...

>    3.   Base64url decode the Encoded JOSE Header following the
        restriction that no line breaks, whitespace, or other additional
        characters have been used.


As said before, I'm not willing to reduce how strict we are with the regex but I definitely agree we should have a better user/dev/ops experience and add a log statement when the jwt couldn't be validated.

**Comment by soskamp** [comment]
That's fine with me, I can simply use my patched version in my use case.
Should I close the PR then?

**Comment by soskamp** [comment]
As discussed, regex should not be relaxed.

**Comment by tuunit** [comment]
> That's fine with me, I can simply use my patched version in my use case.
> Should I close the PR then?

If you are still willing to contribute it would be great to repurpose this PR and add a log statement instead :)

**Pull request closed without merging**
