### PR TITLE
add oidc issuer to Azure auth provider doc

### PR DESCRIPTION
**Pull request by weinong**
## Description
update Azure auth provider doc to include oidc issuer option which is used to verify id_token

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
What's the difference between setting the issuer this way and using the azure tenant flag?

**Comment by weinong** [comment]
> What's the difference between setting the issuer this way and using the azure tenant flag?

using azure tenant flag doesn't set the issuer as azure provider never verifies the token until oidc issuer  is set

**Comment by JoelSpeed** [comment]
@weinong Ok that makes sense, could you please copy the change to the versioned documentation as well please?

@wosc I think that would probably make sense, though at the moment, we are going through some major changes with the providers and trying to reduce the amount of code we are maintaining within them. I'd prefer we keep a note of this and implement the functionality post all of this refactoring so we don't make things even more complicated while we are working on this

**Comment by LouisStAmour** [comment]
Note the suggestion in this PR is for v1 tokens. For v2 tokens the issuer changes to `https://login.microsoftonline.com/---insert-tenant-id-here---/v2.0` to match that of `https://login.microsoftonline.com/---insert-tenant-id-here---/discovery/v2.0/keys` which can be found from `https://login.microsoftonline.com/---insert-tenant-id-here---/v2.0/.well-known/openid-configuration`

**Comment by weinong** [comment]
> Would it be feasible for oauth2-proxy to calculate the issuer url from the tenant ID? Then you'd have to specify it only once, in `--tenant=MYTENANT` and not twice additionally with `--oidc-issuer-url=.../MYTENANT`. (Not to detract from this docs change, just thinking out loud.)

since `--tenant` is optional so I would probably not want to derive from it.

@JoelSpeed, updated versioned doc.

@LouisStAmour unfortunately, azure provider uses adal which requires v1 issuer format. v2 issuer format works only with generic oidc provider.

**Comment by LouisStAmour** [comment]
What does ADAL offer that the generic provider lacks? From what I’ve tested both v1 and v2 work great with the generic oidc. It’s not clear to me why I would want to use a custom provider? :)

Especially if issuer isn’t being inferred, etc. And if all the provider does is let me not have to infer a URL, well, we could save a lot of code just by re-using the generic oidc instead…

**Comment by weinong** [comment]
@LouisStAmour if you want to get access token for an AAD resource, oidc will not be able to satisfy. Also, due to the lack of v2 support in the golang sdk, obtaining access token supports v1 endpoint only.

**Comment by LouisStAmour** [comment]
@weinong Interesting. Looks like there’s already talk of expanding the generic oidc code to handle this use case: https://github.com/oauth2-proxy/oauth2-proxy/issues/1140 Microsoft’s implementation appears to be standard, and documented at https://docs.microsoft.com/en-us/azure/active-directory-b2c/openid-connect#get-a-token so again, I suspect we would be able to switch to a generic oidc provider once a config setting exists for response_code in the generic provider, etc.

Personally I would have more faith in the security and implementation of OAuth2-proxy if there was one code flow that could handle all (standard) endpoints without needing to pick different provider-specific implementations. I recognize that provider-specific implementations can have additional security measures or conveniences but it would seem to me that a standard set of functionality is better tested and supported than trying to keep up with bug fixes or third-party dependencies in well, third-party dependencies?

**Comment by weinong** [comment]
@LouisStAmour interesting read! looking forward to it!

**Comment by weinong** [comment]
@JoelSpeed is there anything else you want me to change?

**Comment by weinong** [comment]
@JoelSpeed looking for feedback. thanks!

**Comment by JoelSpeed** [comment]
I think this is fine to merge for now, but long term, we will be replacing the Azure provider with a V2 compatible version based on the OIDC provider, so we will fix up the tenant vs oidc issuer discrepancy later

**Review by JoelSpeed — APPROVED** [review]

**Pull request merged**
