### PR TITLE
Provide a link to the Helm chart for oauth2-proxy

### PR DESCRIPTION
**Pull request by robin-wayve**
## Description

Provide a link to the Helm chart for oauth2-proxy in `installation.md`

## Motivation and Context

See discussion in #608.

## How Has This Been Tested?

This is just a documentation update, but please let me know if I have missed any requirements.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
Looks good, do you think it's worth adding to the latest versioned documentation as well? Else this will only show up on the "next version" for now

**Comment by robin-wayve** [comment]
> Looks good, do you think it's worth adding to the latest versioned documentation as well? Else this will only show up on the "next version" for now

Sure: were you thinking https://github.com/oauth2-proxy/manifests/tree/oauth2-proxy-3.3.2 or https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy/3.3.2 ?

**Comment by JoelSpeed** [comment]
Sorry, I meant in our documentation, we have the core docs (next version) and the already published versions (eg https://github.com/oauth2-proxy/oauth2-proxy/tree/master/docs/versioned_docs). If you only merge into the core docs as you have already, the updated link won't appear until we cut our next release

**Comment by robin-wayve** [comment]
My bad, I see what you meant now, and done!

**Review by JoelSpeed — APPROVED** [review]
Perfect! Thank you

**Pull request merged**
