### PR TITLE
Adapts the SameSite property in case of the "SameSite=None" Apple issue

### PR DESCRIPTION
**Pull request by sneko**
## Description

SameSite=None is not recognized by "old" Apple devices and default it to "Strict". It makes things complicated...

I described in details the issue I had https://github.com/oauth2-proxy/oauth2-proxy/issues/830 you will find some context in it :) . But roughly, in case the device is victim of this issue, I set "Lax" to at least allow CORS requests.

## Motivation and Context

I'm not sure having specific code for Apple is a good thing. But if you look on internet, they are hundreds of people complaining about this Apple issue for iOS12/13 but also MacOSX <=10.4

It would be easier if Apple was putting some effort on it, but they totally left us behind...

## How Has This Been Tested?

I built a docker image and deployed it in my cluster, I tested it on my iOS 12 in native app and browsers, but also on my desktop to check the default behavior was still working (for Chrome & co)

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [X] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by johejo** [comment]
Related https://bugs.webkit.org/show_bug.cgi?id=188165
Buggy webkit seems to behave with Strict if the SameSite attribute is added.  Isn't the solution to remove the SameSite attribute with http.SameSite(0)?
https://github.com/golang/go/blob/release-branch.go1.15/src/net/http/cookie.go#L221-L230

**Comment by sneko** [comment]
@johejo that what I thought but at start in case of Apple devices I set "" as value (the default one) and it was not working at all. Just using "lax" was giving me some good results 😢

**Comment by johejo** [comment]
I used to scratch a server with similar functionality to oauth2-proxy.  
The hack against Webkit's bug at that time is to not send the SameSite attribute to iOS 12 or lower.  
iOS 13 and above worked fine with SameSite Lax. 
But iOS 12.0 and iOS 12.1 got into a redirect loop with this hack.  
Unfortunately I don't know about macOS.
However, such hacks are unlikely to be accepted by oauth2-proxy maintainers.

**Comment by sneko** [comment]
New commit: I moved a bit the MacOSX version condition because at start forums were saying that MacOSX 10.14.x was also having this bug, but after testing with some colleagues, it appear they succeed with "SameSite=None" cookie.

**Comment by NickMeves** [comment]
Since the `UserAgent` header can be tampered/spoofed from malicious clients, I don't want to support any server side functionality that is based off of it.

You can configure the SameSite settings of the session cookie with `--cookie-samesite` configuration to a setting that works for your user population as an alternative.

**Comment by sneko** [comment]
@NickMeves since that's an issue with Apple devices depending on version... there is no magic way to just "target the user population".

If it cannot be inside the proxy, I would have to deploy 2 proxies and route depending on the user agent...

**Comment by NickMeves** [comment]
Are you able to use the `--cookie-samesite` option to at least get a setting that works for your user community, even if it reduces the security posture?

Otherwise, I think you might need to maintain your own fork if you need this feature.

We're making a concerted effort to streamline the organization of the codebase to improve the long term maintenance of the project while giving structured interfaces for pluggable aspects of the code to implement new options (oauth providers, session stores, configuration sources, etc).

We're struggling to keep up with all the corner case hacks we have for various Identity Providers' weird implementations (I feel like at least 5 issues/PRs have popped up with IdPs implementing the unofficial `groups` claim oddly, making the new Group functionality a mess).

Therefore, I'm very hesitant to add corner case handling around end user client variations as well.

**Comment by NickMeves** [comment]
Do `http.SameSiteDefaultMode` (the default) or `http.SameSiteLaxMode` work for your whole user population? I see on the support grid those are both valid for IOS 12.2 -- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

I think I might have a similar setup as you, where I have a common corporate domain (E.g. `.company.com`) for my `--cookie-domains` and `--whitelist-domains` with multiple internal applications sharing a single access proxy. I don't think I needed to update `--cookie-samesite` if I recall, I stuck with the default which results in `http.SameSiteDefaultMode`.

**Comment by sneko** [comment]
@NickMeves I think that's the difference between your case and mine: making POST requests (CORS) to a protected environment. So if auth cookies are not passed along the request it fails against the proxy, and this is due to Apple and their weird way of managing Lax/Strict 👎

**Pull request closed without merging**
