### PR TITLE
Support TLS 1.3

### PR DESCRIPTION
**Pull request by aajisaka**
## Description

Set "tls.MaxVersion = tls.VersionTLS13" to use TLS 1.3 if possible.

## Motivation and Context

Now the TLS version is hard-coded and it does not support TLS 1.3.

## How Has This Been Tested?

Manually tested. I compiled and deployed in CentOS 7 and ran curl command.

```
% curl -i -v https://<hostname>:<port> --tlsv1.3
```

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by aajisaka** [comment]
Oh, I saw #833 after opening the PR.

**Comment by JoelSpeed** [comment]
Please add a note to the changelog mentioning this change and I'm happy to get this merged

**Comment by aajisaka** [comment]
Thank you @JoelSpeed for your review. Added a note to the changelog.

BTW, I found an existing typo `oauth2-rpoxy/pull/911` in the changelog. Should I fix this in this PR?

**Comment by NickMeves** [comment]
> Thank you @JoelSpeed for your review. Added a note to the changelog.
> 
> BTW, I found an existing typo `oauth2-rpoxy/pull/911` in the changelog. Should I fix this in this PR?

Go for it - Thanks!

**Review by JoelSpeed — APPROVED** [review]
LGTM, thanks!

**Comment by aajisaka** [comment]
Thank you @JoelSpeed and @NickMeves !

**Pull request merged**
