### PR TITLE
Support MinimalLogLevel and adding request to error logs.

### PR DESCRIPTION
**Pull request by MNF**
## Description

Support MinimalLogLevel in configuration, e.g.
  - --minimal-log-level=INFO #normally INFO, for debugging change to TRACE see https://pkg.go.dev/github.com/juju/loggo#Level

In code, use logger.LogTracef(format string, v ...interface{})  depends on loggo.Level

Also  adding request to error logs, to see details of request even if  - --request-logging=false

## Motivation and Context

Allows to control level of logging from configuration
Also  adding request to error logs, to see details of request even if  - --request-logging=false

Support ability to log debug details #1134 
Include Request details in error logs   #1324 

## How Has This Been Tested?
The functionality is used for some time in private forks.

## Checklist:

- [X] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
I have some concerns about logging the request objects, surely there's a lot of information in there that isn't really needed/bloats the logs a bit? Would it be more useful to log a subset of the request?

I need to do some research into this loggo package, not heard of that one before

**Comment by NickMeves** [comment]
CC: @Bibob7 

You've had a good perspective in the past on privacy focused jurisdictions where us logging certain data types is an issue (email if I recall)?

**Comment by JoelSpeed** [comment]
This conversation keeps coming up, we need to decide how we want to proceed. I'm not sure logging the whole request object is something we actually want to do for example, unless someone can come up with a very compelling use case that will change my mind

**Comment by benjroesner** [comment]
@JoelSpeed Can this PR be reconsidered please? The detailed log level would be very helpful in some cases.

**Comment by tuunit** [comment]
@benjroesner sorry but we want to migrate to structured logging with log levels using slog in the future.

**Pull request closed without merging**
