### PR TITLE
Extract Keycloak roles while creating a session from token

### PR DESCRIPTION
**Pull request by MrDeerly**
## Description
While creating a new Session from an AuthToken the Keycloak roles needs to be extracted. Otherwise they're not part of the session which will break the authentication. (AllowedGroups doesn't match givenGroups.. because it's empty). Since `CreateSessionFromToken` was already used from the OIDC provider, adding a single line shouldn't break anything.

## Motivation and Context
The main motivation is to fix https://github.com/oauth2-proxy/oauth2-proxy/issues/1457#. It blocks user's from authenticating via token in combination with role checks

## How Has This Been Tested?

Besides alot of manual testing I've also added a small unit test.

To reproduce the issue you need to create an Keycloak Client and a user. Create a auth token and try to authenticate against the proxy using the token.  Use the following settings for the proxy:
``
          "--client-id=xxxxx",
          "--client-secret=xxxx",
          "--upstream=xxxxx",
          "--oidc-issuer-url=xxxxxx",
          "--redeem-url=xxxxxx",
          "--redirect-url=xxxxxx",
          "--http-address=xxxxx",
          "--auth-logging=true",
          "--email-domain=*",
          "--cookie-secret=xxxx",
          "--standard-logging=true",
          "--auth-logging=true",
          "--request-logging=true",
          "--whitelist-domain=xxxxxxx",
          "--skip-provider-button=true",
          "--skip-jwt-bearer-tokens=true",
          "--pass-authorization-header=true",
          "--pass-access-token=true",
          "--pass-user-headers=true",
          "--allowed-role=realm-access-role",
          "--cookie-secure=false",
          "--scope=openid email profile",
          "--skip-auth-route=/health"``

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by DrPsychick** [comment]
Any chance this can be reviewed and merged?

**Comment by JoelSpeed** [comment]
This looks reasonable, thanks! 

Could you fixup the changelog conflict and I'll get it merged

**Review by JoelSpeed — APPROVED** [review]

**Comment by JethroMV** [comment]
Hey, I think I'm hitting this issue. Are there any plans for a release including this fix? The latest release (v7.3.0) was from before this was merged.

**Comment by JoelSpeed** [comment]
Hoping to cut a release soon, need to find the time to sit down and do it

**Pull request merged**
