### PR TITLE
Added AllowedGroupsHeader option

### PR DESCRIPTION
**Pull request by turbotankist**
## Description
Added option `--allowed-groups-header` (`allowed_groups_header` in configfile) which allow us to authorize logins based on groups in request header.
The `allowed-groups-header` and `allowed-groups`  options are checked independently, and both must match user groups.

## Motivation and Context
This allow:
1. Use single oauth2-proxy deployment for multiple applications 
2. Authorize different path for differents groups

## How Has This Been Tested?

Deployed using helm chart in kubernetes 
with istio.

I'he done this:
1. Run oauth2-proxy with `--allowed-groups-header=X-Header-Allowed-Groups-Example` option

2. added to istio MeshConfig
```
    extensionProviders:
    - name: oauth2-proxy
      envoyExtAuthzHttp:
        service: oauth2-proxy.oauth2-proxy.svc.cluster.local
        port: 80
        timeout: 2s
        includeHeadersInCheck: ["authorization", "cookie", "X-Header-Allowed-Groups-Example"] ## <--
        headersToUpstreamOnAllow: ["x-forwarded-access-token", "authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token"]
        headersToDownstreamOnDeny: ["content-type", "set-cookie"]
```
3. created istio AuthorizationPolicy:
```
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: myaplication
spec:
  selector:
    matchLabels:
      app: myaplication   ## must match Myapp sidecar / not gateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts: ["protectme.mycompany.com"]
            noPaths: ["/public"]
```
On this point enought to authorize users based on `allowed-groups` option in oauth2-proxy. 
But we want more

4. created istio virtualservice
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: myaplication
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - protectme.mycompany.com
  http:
  - match:
    - uri:
        prefix: "/admins"
    headers:
      request:
        set:                 ## 'set' - adds header and override it if request already has it
          X-Header-Allowed-Groups-Example: AD-Myapp-Admins  ## header name eq --allowed-groups-header
    route:
    - destination:
        host: myaplication
        port:
          number: 443
  - match:
    - uri:
        prefix: "/managers"
    headers:
      request:
        set:
          X-Header-Allowed-Groups-Example: AD-Myapp-Manager,AD-Myapp-Admins
    route:
    - destination:
        host: myaplication
        port:
          number: 443
  - headers:
      request:
        set:
          X-Header-Allowed-Groups-Example: AD-Myapp-Users,AD-Myapp-Manager,AD-Myapp-Admins
    route:
    - destination:
        host: myaplication
        port:
          number: 443
```
5. 
- Users in AD-Myapp-Admins group could access to `protectme.mycompany.com/` with all paths 
- Users in AD-Myapp-Manager group could access to `protectme.mycompany.com/` except `/admins`
- Users in AD-Myapp-Users group could access to `protectme.mycompany.com/` except `/admins` and `/managers`
- `protectme.mycompany.com/public` - allowed access everybody (we excluded it in AuthorizationPolicy)

6. Also the users should have any group from `allowed-groups` additionally to groups from the header 

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by turbotankist** [comment]
Is it ok?

**Comment by JoelSpeed** [comment]
Apologies for the delay, I'll try to review this soon

**Comment by wccropper** [comment]
Will this PR also allow this #1855 to work?

**Comment by jonbonazza** [comment]
Hi, we are looking to use oauth2-proxy at Epic Games and this would be a necessary feature for us. Is there a chance that this could be merged?

**Comment by JoelSpeed** [comment]
I believe #1286 already solved this use case

**Comment by jonbonazza** [comment]
Hi @JoelSpeed , I dont think that PR satisfies our use case. We want to be able to authorize different paths with different scopes in the JWT. With this PR, it doesnt completely satisfy our use case in that wed still need an nginx proxy in front to rewrite the header based on path, but it gets us most of the way there from what I can see.

If this particular implementation isnt ideal, perhaps we can come up with a better one to solve our use case?

**Comment by JoelSpeed** [comment]
> Hi @JoelSpeed , I dont think that PR satisfies our use case. We want to be able to authorize different paths with different scopes in the JWT. With this PR, it doesnt completely satisfy our use case in that wed still need an nginx proxy in front to rewrite the header based on path, but it gets us most of the way there from what I can see.
> 
> If this particular implementation isnt ideal, perhaps we can come up with a better one to solve our use case?

Are you trying to avoid having Nginx in front? In general, my recommendation for folks is that they use OAuth2 Proxy as a sidecar for auth and use a fully fledged, dedicated proxy project where possible for their actual proxying. While OAuth2 Proxy specialises in authentication, the proxying decisions, rewrites etc are handled better by these other proxies. My vision for this project is that it can be composed with other proxies to extend them to achieve the kinds of solutions you want. IMO we've already added more proxy features than I would have liked to have, but there's little we can do about that now

**Comment by jonbonazza** [comment]
Asking our users to setup two proxies would be kind of annoying from their perspective, but one we could probably live with. It’s not clear to me however how I could implement what Im looking for using nginx, without writing a bunch of lua code to crack open the jwt etc… ideally, if we used nginx or haproxy or something behind oauth2-proxy, we’d do it without a heavy luajit module or such. 

Is there any way to get the groups from the token from the headers or such when the request is proxied through?

**Comment by JoelSpeed** [comment]
> Is there any way to get the groups from the token from the headers or such when the request is proxied through?

Yes there is, if you look at options for returning headers from the proxy, these can then be copied across using nginx's auth_request module

**Pull request closed without merging**
