### PR TITLE
20220802 fix nextcloud

### PR DESCRIPTION
**Pull request by n1tehawk**
This PR addresses #1749.

## Description

In order to work with recent oauth2-proxy, the Nextcloud provider seems to require a fix to use the `Authorization: Bearer`+*token* header, and an `EnrichSession()` implementation.

## How Has This Been Tested?

oauth2-proxy protected site via nginx, authenticating against Nextcloud 23.0.5

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.
- [ ] Unit tests need to be added for the new provider/EnrichSession functionality.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
Changes look good, can you please run gofmt over the file and then add a changelog entry

**Comment by JoelSpeed** [comment]
Please make sure to fix the linter issues as well

**Comment by n1tehawk** [comment]
I have addressed the linter issue, updated CHANGELOG.md, and rebased my branch onto current `master`. Regards, NiteHawk

**Review by Sykar77 — APPROVED** [review]

**Review by JoelSpeed — APPROVED** [review]

**Comment by ThisIsQasim** [comment]
In case someone else is trying to use oauth2-proxy with multiple hostnames and Nextcloud as IDP with broken redirects, [this](https://github.com/nextcloud/server/issues/29317#issuecomment-1279809795) might help

**Pull request merged**
