### PR TITLE
Drop configure script in favour of native Makefile env and checks

### PR DESCRIPTION
**Pull request by JoelSpeed**
## Description

Drops the configure script requirement for using our Makefile

## Motivation and Context

The configure script doesn't add too much other than checking the minimum Go version.
We can do this in the Makefile anyway, so that's what is done here

## How Has This Been Tested?

```
$ docker run --rm -it -v $PWD:/go/src/github.com/oauth2-proxy/oauth2-proxy golang:1.13 make -C src/github.com/oauth2-proxy/oauth2-proxy build
make: Entering directory '/go/src/github.com/oauth2-proxy/oauth2-proxy'
Golang version is not supported, please update to at least 1.14
make: *** [Makefile:76: validate-go-version] Error 1
make: Leaving directory '/go/src/github.com/oauth2-proxy/oauth2-proxy'
```

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by steakunderscore** [comment]
Oh and the Dockerfiles

**Comment by JoelSpeed** [comment]
I've done a find and replace, no more configures to be seen!

Should we note this as a breaking change? It's not for the product but could be for developers who may have set up their `.env` files specifically?

**Comment by gargath** [comment]
The only thing this particular `configure` script allowed users to customize is the location of `go`. I do not believe that will have been used much by anyone, so I don't think this constitutes a breaking change.

**Comment by JoelSpeed** [comment]
Sorry @gargath I did a rebase and dismissed your review

**Pull request merged**
