### PR TITLE
Add OIDC group membership validation

### PR DESCRIPTION
**Pull request by teodor-pripoae**
Hi,

I've updated oauth2 proxy to allow group membership validation for OIDC providers.

## Description

Validate the groups returned by OIDC provider contain at least one group provided by command line/environment.

## Motivation and Context

We are trying to restrict access based on specific OIDC groups similar to Github teams/groups.

## How Has This Been Tested?

I've added a few tests and tested locally with Dex with LDAP backend.

## Checklist:

I made OIDC Group a string instead of string slice becouse specific implementations can contain comma in group name (for example groups returned by LDAP provider like `cn=Users,domain=example,domain=com`). Group name separation is done using `;`.

### CODE REVIEW

**Comment by NickMeves** [comment]
Hey there! We are actually wrapping up this functionality in this PR here: https://github.com/oauth2-proxy/oauth2-proxy/pull/616

Can you let us know if this PR has any functionality missed in that PR? Otherwise we can close this as a duplicate.

**Comment by teodor-pripoae** [comment]
No, I think it implements the same functionality. The only thing which gets in my mind is when the group name contains `,`.  Is the flag library splitting the flags by comma ?

I mean if the user specifies `--allowed-groups 'dn=Users,dc=example,dc=com'`, it will be 3 groups or only one ?

**Comment by NickMeves** [comment]
> No, I think it implements the same functionality. The only thing which gets in my mind is when the group name contains `,`. Is the flag library splitting the flags by comma ?
> 
> I mean if the user specifies `--allowed-groups 'dn=Users,dc=example,dc=com'`, it will be 3 groups or only one ?

Throughout the configurations, the convention for things that can be plural is when used as a flag, you specific the flag multiple times in its singular english form. When used in a configuration file or environment variable, it has the `s` on the end and multiple values are split by `,` (default behavior with the `spf13/viper` package we use for configuration options).

**Comment by JoelSpeed** [comment]
We may need to switch from a `StringSlice` to a `StringArray`, if we do so, multiple values wouldn't be split on commas. 
`'dn=Users,dc=example,dc=com'` is meant to represent a single group, but a `StringSlice` would break that.

If this is a duplicate, can we comment on the other issue with any changes that need including and then close this PR?

**Comment by NickMeves** [comment]
Duplicate of #616 which merged

**Pull request closed without merging**
