### PR TITLE
Embed static stylesheets and dependencies

### PR DESCRIPTION
**Pull request by corybolar**
Embedding css and webfont dependencies allows the application to present itself correctly in an environment that does not allow downloading the files from a cdn.

Inspiration taken from #1492 but reworked to make use of embed.FS simplifying the approach.

## Description

Embed necessary stylesheets and their dependencies within the application at build time and serve them to user's under the /static/ path prefix.

## Motivation and Context

Without the ability to pull stylesheets from the configured cdn addresses, oauth2-proxy's appearance is lacking.

## How Has This Been Tested?

Build the application and test with and without the --proxy-prefix option to ensure sign-in and error pages load correctly.  Network can be disconnected or the network inspection tab on the browser can be used to verify css files are pulled from the application.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.

### CODE REVIEW

**Comment by corybolar** [comment]
Checking in and curious to know if there is anything objectionable in these changes.  The inclusion of the webfonts is necessary only to satisfy the existing error page.  Would this be more acceptable if that error page were changed to not depend on external fonts and allow us to drop the webfonts file?

**Comment by corybolar** [comment]
Resolved merge conflicts.  Any feedback to make this more palatable would be appreciated.

**Comment by Mahesh-Gunda-Maersk** [comment]
hello @corybolar, when this PR will be merged? This change greatly help us with the CSS style sheets

**Comment by tuunit** [comment]
@JoelSpeed looks good to me. The embed feature is stable since go 1.16 and nothing fancy has been done here. Can be merged in my opinion.

@corybolar thanks for the PR.

**Comment by tuunit** [comment]
@corybolar could you please do a rebase of the master branch of the upstream repo. Thank you.

**Comment by corybolar** [comment]
@tuunit @JoelSpeed Branch has been rebased.  Thanks!

**Review by JoelSpeed — APPROVED** [review]
Thanks for working on this

**Pull request merged**
